services:
  desktop:
    build: .
    image: ubuntu-xrdp-lxqt:local
    container_name: desktop
    ports:
      - "${HOST_RDP_PORT:-3389}:3389/tcp"
    environment:
      USER: ubuntu
      PASSWORD: ubuntu
    volumes:
      - home:/home
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  home: {}
